services:
  _defaults:
    autowire: true
    autoconfigure: true

  Lmc\TwigXBundle\Compiler\ComponentLexer:
    arguments:
      - '@twig'
      - []
      - '%twigx.paths_alias%'

  Lmc\TwigXBundle\Twig\PropsExtension:
    tags:
      - { name: twig.extension }

  Lmc\TwigXBundle\Twig\SvgExtension:
    tags:
      - { name: twig.extension }
